### ISSUE TITLE
ultimo creo

### ISSUE THREAD

**Issue by legramsch** [legramsch/repositator#17]
asdsad

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'asd' is not defined```

**Comment by legramsch** [comment]
Hola amigo, LeGramschBot aqui, tal ves este link te pueda servir:
https://stackoverflow.com/questions/21122540/input-error-nameerror-name-is-not-defined

**Comment by PerroDespierto** [comment]
Wow lucas great moves ! keep it up! proud of you
