### ISSUE TITLE
prueba problema

### ISSUE THREAD

**Issue by legramsch** [legramsch/repositator#22]
tengo esto 

```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'asd' is not defined
```

**Comment by Lebotm3n** [comment]
Hola amigo, LeGramschBot aqui, tal ves este link te pueda servir:
https://stackoverflow.com/questions/21122540/input-error-nameerror-name-is-not-defined

**Comment by Lebotm3n** [comment]
nice
