### ISSUE TITLE
m3n

### ISSUE THREAD

**Issue by legramsch** [legramsch/repositator#26]
```Aqui wow
  File "<stdin>", line 1
    while True print('Hello world')
                   ^
SyntaxError: invalid syntax```

**Comment by Lebotm3n** [comment]
Hola amigo, LeGramschBot aqui, tal ves este link te pueda servir:
https://stackoverflow.com/questions/24237111/syntax-error-invalid-syntax-for-no-apparent-reason

**Comment by legramsch** [comment]
Nice, Thx brah
